Fix py2 to py3 issue in crefi_helper.py
Problem:
Crefi fails with the below traceback when tried to run
using python3:
Traceback (most recent call last):
2020-06-22 16:52:24,172 - thread-2: Entering the directory level00
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/crefi-2.0.8-py3.6.egg/crefi_helper.py", line 349, in multipledir
    dir_path)
  File "/usr/local/lib/python3.6/site-packages/crefi-2.0.8-py3.6.egg/crefi_helper.py", line 114, in text_files
    fil = dir_path+"/"+get_filename(flen)
  File "/usr/local/lib/python3.6/site-packages/crefi-2.0.8-py3.6.egg/crefi_helper.py", line 99, in get_filename
    char = string.uppercase+string.digits
AttributeError: module 'string' has no attribute 'uppercase'

This is becuase in python3 string.uppercase is changed to
string.ascii_uppercase.

Fix:
Adding code to handle this in both python2 and python3

Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>